site_name: My Docs

nav:
  - Home: index.md
  - Layers: layers.md
  - Activations: activations.md
  - Losses: losses.md
  - Model: model.md
  - Configuration: config.md
  - Generator: generator.md
  - Training: training.md
